# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Example_QtDesigner_002.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_000(object):
    def setupUi(self, MainWindow_000):
        MainWindow_000.setObjectName("MainWindow_000")
        MainWindow_000.resize(800, 697)
        self.centralwidget = QtWidgets.QWidget(MainWindow_000)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(130, 600, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 600, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 600, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(30, 190, 291, 401))
        self.listView.setObjectName("listView")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setGeometry(QtCore.QRect(590, 620, 193, 28))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 170, 311, 471))
        self.groupBox.setObjectName("groupBox")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(360, 590, 391, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(350, 40, 431, 511))
        self.listWidget.setObjectName("listWidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(400, 10, 201, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(520, 560, 201, 20))
        self.label_2.setObjectName("label_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(210, 10, 120, 151))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(31, 10, 141, 151))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../LoadWorkDataAirFlightsDBNew/Значки (Иконки)/company.ico"))
        self.label_3.setObjectName("label_3")
        self.groupBox.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.listView.raise_()
        self.buttonBox.raise_()
        self.progressBar.raise_()
        self.listWidget.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.frame.raise_()
        self.label_3.raise_()
        MainWindow_000.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow_000)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        MainWindow_000.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_000)
        self.statusbar.setObjectName("statusbar")
        MainWindow_000.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_000)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_000)

    def retranslateUi(self, MainWindow_000):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_000.setWindowTitle(_translate("MainWindow_000", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow_000", "Button_001"))
        self.pushButton_2.setText(_translate("MainWindow_000", "Button_002"))
        self.pushButton_3.setText(_translate("MainWindow_000", "Button_000"))
        self.groupBox.setTitle(_translate("MainWindow_000", "GroupBox"))
        self.label.setText(_translate("MainWindow_000", "TextLabel"))
        self.label_2.setText(_translate("MainWindow_000", "TextLabel"))
